--- 
artifacts: 
  files: 
    - target/*.json
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "mvn clean compile test -Dtest=getcoindata"
  install: 
    runtime-versions: 
      java: corretto11
  post_build: 
    commands: 
      - "echo Build completed on `date`"
  pre_build: 
    commands: 
      - "echo Nothing to do in the pre_build phase..."
version: 0.2
